"use client"
import { useState, useEffect } from "react"
import { SAFETY_PLAN } from "@/lib/day2Data"
import styles from "./SafetyPlan.module.css"

export default function SafetyPlan({ lang, onClose }) {
  const data = SAFETY_PLAN[lang] || SAFETY_PLAN.en
  const [checked, setChecked]   = useState({})
  const [copied,  setCopied]    = useState(false)
  const [section, setSection]   = useState(null) // expanded section id

  // ESC closes
  useEffect(() => {
    const h = (e) => { if (e.key === "Escape") onClose() }
    window.addEventListener("keydown", h)
    return () => window.removeEventListener("keydown", h)
  }, [onClose])

  const toggle = (secId, idx) => {
    const key = `${secId}-${idx}`
    setChecked(prev => ({ ...prev, [key]: !prev[key] }))
  }

  const totalItems   = data.sections.reduce((n, s) => n + s.items.length, 0)
  const checkedCount = Object.values(checked).filter(Boolean).length
  const pct          = Math.round((checkedCount / totalItems) * 100)

  const copyPlan = () => {
    const lines = [`${data.title}\n${"=".repeat(data.title.length)}\n`]
    data.sections.forEach(sec => {
      lines.push(`\n${sec.title}`)
      sec.items.forEach((item, idx) => {
        const key = `${sec.id}-${idx}`
        lines.push(`  ${checked[key] ? "✓" : "○"}  ${item}`)
      })
    })
    lines.push(`\nProgress: ${checkedCount}/${totalItems} (${pct}%)`)
    lines.push("\n— Generated by Aegis Haven · aegis-haven.app")
    navigator.clipboard.writeText(lines.join("\n")).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    })
  }

  const print = () => window.print()

  return (
    <div className={styles.overlay} role="dialog" aria-modal="true" aria-label={data.title}>
      <div className={styles.modal}>

        {/* Header */}
        <div className={styles.header}>
          <div className={styles.headerLeft}>
            <div className={styles.icon}>📋</div>
            <div>
              <h2 className={styles.title}>{data.title}</h2>
              <p className={styles.subtitle}>{data.subtitle}</p>
            </div>
          </div>
          <button className={styles.closeBtn} onClick={onClose} aria-label="Close">✕</button>
        </div>

        {/* Progress bar */}
        <div className={styles.progressWrap}>
          <div className={styles.progressBar}>
            <div className={styles.progressFill} style={{ width: `${pct}%` }} />
          </div>
          <span className={styles.progressLabel}>{checkedCount}/{totalItems}</span>
        </div>

        {/* Sections */}
        <div className={styles.sections}>
          {data.sections.map(sec => {
            const secChecked = sec.items.filter((_, idx) => checked[`${sec.id}-${idx}`]).length
            const open = section === sec.id
            return (
              <div key={sec.id} className={`${styles.section} ${open ? styles.sectionOpen : ""}`}>
                <button
                  className={styles.sectionHead}
                  onClick={() => setSection(open ? null : sec.id)}
                >
                  <span className={styles.sectionTitle}>{sec.title}</span>
                  <span className={styles.sectionCount}>{secChecked}/{sec.items.length}</span>
                  <span className={styles.chevron}>{open ? "▲" : "▼"}</span>
                </button>

                {open && (
                  <div className={styles.items}>
                    {sec.items.map((item, idx) => {
                      const key = `${sec.id}-${idx}`
                      return (
                        <label key={key} className={styles.item}>
                          <span className={`${styles.checkbox} ${checked[key] ? styles.checked : ""}`}>
                            {checked[key] ? "✓" : ""}
                          </span>
                          <input
                            type="checkbox"
                            checked={!!checked[key]}
                            onChange={() => toggle(sec.id, idx)}
                            className={styles.hiddenInput}
                          />
                          <span className={`${styles.itemText} ${checked[key] ? styles.itemDone : ""}`}>
                            {item}
                          </span>
                        </label>
                      )
                    })}
                  </div>
                )}
              </div>
            )
          })}
        </div>

        {/* Actions */}
        <div className={styles.actions}>
          <button className={styles.copyBtn} onClick={copyPlan}>
            {copied ? "✓ Copied!" : data.copyBtn}
          </button>
          <button className={styles.printBtn} onClick={print}>{data.printBtn}</button>
          <button className={styles.actionClose} onClick={onClose}>{data.closeBtn}</button>
        </div>

        <p className={styles.safetyNote}>
          Nothing on this checklist is saved or stored. Copy or print it to keep it safe.
        </p>
      </div>
    </div>
  )
}
